const foods = [
    {
        label: "Barbeque",
        quality: 3,
        kcal: 4000,
        ingredients: ["meat"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/f/f5/Resource_Barbeque.png",
        value: "barbeque",
    },
    {
        label: "Berry Sludge",
        quality: 3,
        kcal: 4000,
        ingredients: ["bristleBerry", "sleetWheatGrain"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/3/30/Resource_Berry_Sludge.png",
        value: "berrySludge",
    },
    {
        label: "Bristle Berry",
        quality: 0,
        kcal: 1600,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/1/11/Resource_Bristle_Berry.png",
        value: "bristleBerry",
    },
    {
        label: "Cooked Fish",
        quality: 3,
        kcal: 1600,
        ingredients: ["pacuFillet"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/c/c8/Resource_Cooked_Fish.png",
        value: "cookedFish",
    },
    {
        label: "Fried Mushroom",
        quality: 1,
        kcal: 2800,
        ingredients: ["mushroom"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/5/56/Resource_Fried_Mushroom.png",
        value: "friedMushroom",
    },
    {
        label: "Frost Bun",
        quality: 2,
        kcal: 1200,
        ingredients: ["sleetWheatGrain"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/c/cc/Resource_Frost_Bun.png",
        value: "frostBun",
    },
    {
        label: "Frost Burger",
        quality: 6,
        kcal: 6000,
        ingredients: ["barbeque", "frostBun", "lettuce"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/4/47/Resource_Frost_Burger.png",
        value: "frostBurger",
    },
    {
        label: "Gristle Berry",
        quality: 1,
        kcal: 2000,
        ingredients: ["bristleBerry"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/c/cd/Resource_Gristle_Berry.png",
        value: "gristleBerry",
    },
    {
        label: "Lettuce",
        quality: 0,
        kcal: 400,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/f/fe/Resource_Lettuce.png",
        value: "lettuce",
    },
    {
        label: "Liceloaf",
        quality: 0,
        kcal: 1700,
        ingredients: ["mealLice"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/5/5f/Resource_Liceloaf.png",
        value: "liceloaf",
    },
    {
        label: "Meal Lice",
        quality: -1,
        kcal: 600,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/f/f6/Resource_Meal_Lice.png",
        value: "mealLice",
    },
    {
        label: "Meat",
        quality: -1,
        kcal: 1600,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/b/b6/Resource_Meat.png",
        value: "meat",
    },
    {
        label: "Mush Bar",
        quality: -1,
        kcal: 800,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/b/ba/Resource_Mush_Bar.png",
        value: "mushBar",
    },
    {
        label: "Mush Fry",
        quality: 0,
        kcal: 1050,
        ingredients: ["mushBar"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/c/c0/Resource_Mush_Fry.png",
        value: "mushFry",
    },
    {
        label: "Mushroom",
        quality: 0,
        kcal: 2400,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/6/66/Resource_Mushroom.png",
        value: "mushroom",
    },
    {
        label: "Mushroom Wrap",
        quality: 4,
        kcal: 4800,
        ingredients: ["mushroom", "lettuce"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/e/ea/Resource_Mushroom_Wrap.png",
        value: "mushroomWrap",
    },
    {
        label: "Nosh Bean",
        quality: 3,
        kcal: 0,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/d/d2/Nosh_Bean.png",
        value: "noshBean",
    },
    {
        label: "Omelette",
        quality: 2,
        kcal: 2800,
        ingredients: ["rawEgg"],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/3/32/Resource_Omelette.png",
        value: "omelette",
    },
    // stopped here
    {
        label: "Pacu Fillet",
        quality: 2,
        kcal: 1000,
        ingredients: [],
        url: "https://static.wikia.nocookie.net/oxygennotincluded_gamepedia_en/images/0/0b/Resource_Pacu_Fillet.png",
        value: "pacuFillet",
    },
];

export default foods;
